// Golden-vector tests for the Dart wire codec.
//
// The vectors are THE SAME SIX the reference implementations pass
// (meshtech-node tests/golden_vectors.json, generated by
// tools/gen_golden.py; the TypeScript codec passes them too). Every
// test decodes the vector, asserts the fields, re-encodes, and pins
// the bytes - a byte that disagrees with the reference never ships
// (DESIGN.md law: checked against the SAME vectors).
//
// Call contract (matching the reference): the golden vectors are full
// GRP_DATA plaintexts; decodeAny strips the 3-byte envelope and
// dispatches. The typed decode* functions take the BODY only.

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:meshtech_app/codec.dart';

const Map<String, String> golden = {
  'pulse': '0153170513017eb1d20404000900280009090305080200010406',
  'sect_sum': '0253130504007eb101017e003000300300022102cdab',
  'route': '0353120502007eb101efbe38000400110003112233',
  // v1.6 (2026-09-25): the rows byte rides at the end (03 = 3 down).
  // Regenerated with the node's tools/gen_golden.py - the two repos'
  // goldens stay pinned to the same bytes.
  'layout': '0553160503007eb10344d61200a01ce9ff409c0464656d6f03',
  // v1.6 (2026-09-26): the ruler - span field 3 LE bytes (409c00 =
  // 40000 m). Regenerated with the node's tools/gen_golden.py.
  'intro':
      '04531f0602007eb1409c000211030748696c6c746f7024002400220105416c696365',
  // refresh: regenerated 2026-09-24 with the reference (v1.6 REFRESH_REQ:
  // version 06, +2 bytes sync_marker 0000 - the one wire change).
  'refresh': '115310060200420002efbe7eb1341200000000',
  // clinic: the Mesh Clinic packet (CLINIC-WIRE.md) - 4 records
  // (node / route / flag / peer-pulse). Generated with the node's
  // tools/gen_golden.py: the two repos' goldens stay pinned to the
  // same bytes (tests/golden_vectors.json "clinic").
  'clinic':
      '14534f0513017eb10401147eb12103000500070080022514240410a6b09c0a02127eb102112238000002000400090011000200030c7eb1022102001e000500f401040fefbe0100000400d204040028000900',
};

Uint8List bytesOf(String hex) => Uint8List.fromList([
      for (var i = 0; i < hex.length; i += 2)
        int.parse(hex.substring(i, i + 2), radix: 16),
    ]);

String hexOf(Uint8List b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

/// Decode a full golden plaintext through the generic path (the way
/// real traffic arrives), returning the typed packet.
T decodeGolden<T>(String hex) => decodeAny(bytesOf(hex)) as T;

void main() {
  group('PULSE golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final p = decodeGolden<Pulse>(golden['pulse']!);
      expect(p.seq, 275);
      expect(p.origin, 0xb17e);
      expect(p.uptimeMin, 1234);
      expect(p.rxPerHour, 4);
      expect(p.feedAirtimeSPerH, 9);
      expect(p.activeTotal, 40);
      expect(p.sectionCounts, [9, 3, 5, 8, 2, 0, 1, 4, 6]);
      expect(hexOf(encodePulse(p)), golden['pulse']);
    });
  });

  group('SECT_SUM golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final s = decodeGolden<SectSum>(golden['sect_sum']!);
      expect(s.seq, 4);
      expect(s.origin, 0xb17e);
      expect(s.sectionId, 1);
      expect(s.activeNodes, 1);
      expect(s.packetCount, 126);
      expect(s.delayP50S, 48);
      expect(s.delayP90S, 816);
      expect(s.routeStubs, [0x0221, 0xabcd]);
      expect(hexOf(encodeSectSum(s)), golden['sect_sum']);
    });
  });

  group('ROUTE golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final r = decodeGolden<Route>(golden['route']!);
      expect(r.seq, 2);
      expect(r.origin, 0xb17e);
      expect(r.sectionId, 1);
      expect(r.routeId, 0xbeef);
      expect(r.packetCount, 56);
      expect(r.delayMedS, 4);
      expect(r.lastHeardMin, 17);
      expect(r.prefixes, [0x11, 0x22, 0x33]);
      expect(hexOf(encodeRoute(r)), golden['route']);
    });
  });

  group('LAYOUT golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final l = decodeGolden<Layout>(golden['layout']!);
      expect(l.seq, 3);
      expect(l.origin, 0xb17e);
      expect(l.grid, 3);
      expect(l.rows, 3);
      expect(l.centerLat, closeTo(1.2345, 1e-9));
      expect(l.centerLon, closeTo(-1.5, 1e-9));
      expect(l.spanM, 40000);
      expect(l.name, 'demo');
      expect(hexOf(encodeLayout(l)), golden['layout']);
    });

    test('a packet WITHOUT the rows byte is the old square wire', () {
      // Brett's 3x4 (2026-09-25): the rows byte rides AFTER the name
      // so a legacy packet still decodes - as the square it always
      // meant (grid x grid).
      final raw = bytesOf(golden['layout']!);
      final legacy = decodeLayout(raw.sublist(3, raw.length - 1));
      expect((legacy.grid, legacy.rows), (3, 3));
      // And 3x4 round-trips as itself.
      final l = Layout(
          seq: 3, grid: 3, rows: 4, centerLat: 1.2345, centerLon: -1.5,
          spanM: 40000, name: 'demo');
      final out = decodeLayout(encodeLayout(l).sublist(3));
      expect((out.grid, out.rows), (3, 4));
    });
  });

  group('INTRO golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final intro = decodeGolden<Intro>(golden['intro']!);
      expect(intro.seq, 2);
      expect(intro.origin, 0xb17e);
      expect(intro.wireSpanM, 40000); // v1.5: the span rides on the wire
      expect(intro.spanM, 40000.0);
      expect(intro.entries.length, 2);
      final e1 = intro.entries[0];
      expect(e1.prefix, 0x11);
      expect(e1.name, 'Hilltop');
      expect(e1.nodeClass, nodeClassUnknown);
      expect(e1.lat, isNotNull);
      expect(e1.lon, isNotNull);
      // Deltas were 36/36 against a 40000 m span centred at (0, 0).
      final spanDeg = 40000.0 / 111320.0;
      expect(e1.lat!, closeTo(36 / 32767.0 * spanDeg, 1e-12));
      expect(e1.lon!, closeTo(36 / 32767.0 * spanDeg, 1e-12));
      final e2 = intro.entries[1];
      expect(e2.prefix, 0x22);
      expect(e2.name, 'Alice');
      expect(e2.lat, isNull);
      expect(e2.lon, isNull);
      // Re-encode from the decoded values: the position delta math
      // must round-trip exactly (decode -> encode -> same bytes).
      final rebuilt = Intro(
        seq: intro.seq,
        origin: intro.origin,
        entries: intro.entries,
        centerLat: intro.centerLat,
        centerLon: intro.centerLon,
        spanM: intro.spanM,
      );
      expect(hexOf(encodeIntro(rebuilt)), golden['intro']);
    });

    test("the packet's ruler is the truth - a caller span no longer "
        'argues with it', () {
      // Brett's fix (2026-09-26): the span is a RULER measured to fit
      // the data - comparing it to a LAYOUT window is noise, so a
      // disagreeing caller span is ignored (it survives only as the
      // fallback for pre-v1.5 packets).
      final body = bytesOf(golden['intro']!).sublist(3);
      final intro = decodeIntro(body, spanM: 60000);
      expect(intro.wireSpanM, 40000); // the packet's ruler wins
    });

    test('a far node travels TRUE - never pinned at a window edge', () {
      // The pile-of-dots fix: the ruler reaches the node, so its
      // position round-trips true (~90 km out); a ruler that cannot
      // reach refuses loudly instead of faking the position.
      const far = IntroEntry(prefix: 1, name: 'Far', lat: 37.8, lon: -122.0);
      final intro = Intro(
          seq: 1, centerLat: 37.0, centerLon: -122.0, spanM: 150000,
          entries: const [far]);
      final out = decodeIntro(encodeIntro(intro).sublist(3),
          centerLat: 37.0, centerLon: -122.0);
      expect(out.entries.single.lat!, closeTo(37.8, 0.001));
      expect(out.entries.single.lon!, closeTo(-122.0, 0.001));
      expect(
          () => encodeIntro(const Intro(
              seq: 1,
              centerLat: 37.0,
              centerLon: -122.0,
              spanM: 40000,
              entries: [far])),
          throwsCodecError);
    });
  });

  group('REFRESH_REQ golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final r = decodeGolden<RefreshReq>(golden['refresh']!);
      expect(r.seq, 2);
      expect(r.origin, 0x0042);
      expect(r.kind, refreshKindRoute);
      expect(r.target, 0xbeef);
      expect(r.host, 0xb17e);
      expect(r.nonce, 0x1234);
      expect(r.spanKm, 0); // v1.3 field present, host decides
      expect(r.syncMarker, 0); // v1.6 field present, not vectored
      expect(hexOf(encodeRefreshReq(r)), golden['refresh']);
    });

    test('encode round-trips a sized ask (40 km)', () {
      final req = RefreshReq(
          seq: 9, kind: refreshKindSection, target: 5, nonce: 1, spanKm: 40);
      final back = decodeRefreshReq(encodeRefreshReq(req).sublist(3));
      expect(back.spanKm, 40);
      expect(back.kind, refreshKindSection);
      expect(back.target, 5);
    });
  });

  group('strict boundary rules (loud, never silently wrong)', () {
    test('unknown data_type is rejected', () {
      expect(() => decodeBody(0x9999, Uint8List(8)), throwsCodecError);
    });

    test('section_id 0 is reserved and rejected in a SECT_SUM', () {
      final s = const SectSum(
          seq: 1, sectionId: 0, activeNodes: 1, packetCount: 1,
          delayP50S: 0, delayP90S: 0);
      expect(() => encodeSectSum(s), throwsCodecError);
    });

    test('a too-short payload is rejected, not guessed', () {
      expect(
          () => decodePulse(Uint8List.fromList([5, 1, 0])), throwsCodecError);
      expect(
          () =>
              decodeLayout(bytesOf(golden['layout']!).sublist(3, 10)),
          throwsCodecError);
    });

    test('an unknown protocol version is rejected', () {
      final body = bytesOf(golden['pulse']!).sublist(3);
      final bad = Uint8List.fromList(body);
      bad[0] = 0x99; // version byte inside the body
      expect(() => decodePulse(bad), throwsCodecError);
    });

    test('ASCII node names round-trip through INTRO encode', () {
      final intro = Intro(
        seq: 1,
        spanM: 40000,
        entries: const [
          IntroEntry(prefix: 0x11, name: 'Hilltop',
              lat: 0.0, lon: 0.0, nodeClass: nodeClassRepeater),
        ],
      );
      final decoded =
          decodeIntro(encodeIntro(intro).sublist(3));
      expect(decoded.entries.length, 1);
      expect(decoded.entries.single.name, 'Hilltop');
      expect(decoded.entries.single.nodeClass, nodeClassRepeater);
      expect(decoded.entries.single.lat, 0.0);
    });
  });

  heartbeatTests();
  clinicTests();
}

/// CLINIC (0x5314) golden + boundary tests - byte-parity with the
/// node codec, and loud refusals wherever the wire page demands them.
void clinicTests() {
  group('CLINIC golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final c = decodeGolden<Clinic>(golden['clinic']!);
      expect(c.seq, 275);
      expect(c.origin, 0xb17e);
      expect(c.records.length, 4);

      final n = c.records[0] as ClinicNodeFact;
      expect(n.source, 0xb17e); // source == origin: first-hand
      expect(n.prefix, 0x21);
      expect(n.lastAgeMin, 3);
      expect(n.ageDays, 5);
      expect(n.strip, 0x800007);
      expect(n.hopsTyp, 2);
      expect(n.sharePct, 37);
      expect(n.snrEwma, 20);
      expect(n.snrBest, 36);
      expect(n.snrWorst, 4);
      expect(n.snrSd, 16);
      expect(n.rssiEwma, -90);
      expect(n.rssiBest, -80);
      expect(n.rssiWorst, -100);
      expect(n.rssiSd, 10);

      final r = c.records[1] as ClinicRouteFact;
      expect(r.source, 0xb17e);
      expect(r.path, [0x11, 0x22]);
      expect(r.uses, 56);
      expect(r.direct, 0);
      expect(r.delayMinS, 2);
      expect(r.delayMedS, 4);
      expect(r.delayMaxS, 9);
      expect(r.lastAgeMin, 17);
      expect(r.ageDays, 2);

      final f = c.records[2] as ClinicFlagFact;
      expect(f.source, 0xb17e);
      expect(f.flag, flagTsBackwards);
      expect(f.subject, 0x21);
      expect(f.events, 2);
      expect(f.firstAgeMin, 30);
      expect(f.lastAgeMin, 5);
      expect(f.detail, 500);

      final p = c.records[3] as ClinicPeerFact;
      expect(p.source, 0xbeef); // source != origin: second-hand
      expect(p.report, reportPulse);
      expect(p.subject, 0);
      expect(p.heardAgeMin, 4);
      expect(p.values, [1234, 4, 40, 9]);

      expect(hexOf(encodeClinic(c.records, seq: c.seq, origin: c.origin)),
          golden['clinic']);
    });

    test('provenance rides in the bytes: source vs packet origin', () {
      // The whole point of the packet (CLINIC-WIRE.md): source ==
      // origin = first-hand (that box's own radio); source != origin
      // = second-hand (a peer box said it). The comparison is the
      // caller's, but the facts it compares are in the bytes.
      final c = decodeGolden<Clinic>(golden['clinic']!);
      expect((c.records[0] as ClinicNodeFact).source, c.origin);
      expect((c.records[1] as ClinicRouteFact).source, c.origin);
      expect((c.records[2] as ClinicFlagFact).source, c.origin);
      expect((c.records[3] as ClinicPeerFact).source, isNot(c.origin));
    });
  });

  group('CLINIC boundary rules (loud, never silently wrong)', () {
    test('the peer-intro shape: null-island 0/0 = NO position', () {
      const withPos = ClinicPeerFact(
          source: 1,
          report: reportIntro,
          subject: 0x22,
          heardAgeMin: 7,
          cls: nodeClassRepeater,
          lat: 37.5,
          lon: -122.25,
          name: 'Alice');
      const without = ClinicPeerFact(
          source: 1, report: reportIntro, subject: 0x22, heardAgeMin: 7,
          name: 'Bob');
      final wire = encodeClinic(const [withPos, without], seq: 9);
      final back = decodeClinic(wire.sublist(3));
      final a = back.records[0] as ClinicPeerFact;
      expect(a.lat!, closeTo(37.5, 1e-7));
      expect(a.lon!, closeTo(-122.25, 1e-7));
      expect(a.name, 'Alice');
      final b = back.records[1] as ClinicPeerFact;
      expect(b.lat, isNull);
      expect(b.lon, isNull);
      expect(b.name, 'Bob');
    });

    test('a peer intro name longer than 24 B refuses - never truncates', () {
      expect(
          () => encodeClinic(const [
                ClinicPeerFact(
                    source: 1,
                    report: reportIntro,
                    subject: 1,
                    heardAgeMin: 0,
                    name: 'this-name-is-far-too-long-for-the-wire'),
              ], seq: 1),
          throwsCodecError);
    });

    test('more than 7 records is refused (the packet cap)', () {
      final records = [
        for (var i = 0; i < 8; i++)
          ClinicFlagFact(
              source: i,
              flag: flagRateStorm,
              subject: i,
              events: 1,
              firstAgeMin: 1,
              lastAgeMin: 1,
              detail: 0),
      ];
      expect(() => encodeClinic(records, seq: 1), throwsCodecError);
    });

    test('a packet over the 163 B channel cap is refused, not sent', () {
      // 7 fat route facts = 188 B of plaintext: the wire page caps
      // the whole packet at MAX_CHANNEL_DATA.
      final records = [
        for (var i = 0; i < 7; i++)
          ClinicRouteFact(
              source: i,
              path: const [1, 2, 3, 4, 5, 6, 7, 8],
              uses: 1,
              direct: 0,
              delayMinS: 1,
              delayMedS: 1,
              delayMaxS: 1,
              lastAgeMin: 1,
              ageDays: 1),
      ];
      expect(() => encodeClinic(records, seq: 1), throwsCodecError);
    });

    test('a malformed record is rejected, not guessed', () {
      // A node fact of the wrong size.
      final body = BytesBuilder();
      body.add(packHeader(1, 0));
      body.add([1, clinicKindNode, 19]);
      body.add(Uint8List(19));
      expect(
          () => decodeClinic(body.toBytes()),
          throwsCodecError);
      // A route fact with path_len 0 (hand-built: the ENCODER would
      // refuse this - the DECODER must too, never guess a shape).
      final badRoute = BytesBuilder();
      badRoute.add(packHeader(1, 0));
      badRoute.add([1, clinicKindRoute, 3, 1, 0, 0]);
      expect(() => decodeClinic(badRoute.toBytes()), throwsCodecError);
      // And the encoder refuses the same fact.
      expect(
          () => encodeClinic(const [
                ClinicRouteFact(
                    source: 1,
                    path: [],
                    uses: 0,
                    direct: 0,
                    delayMinS: 0,
                    delayMedS: 0,
                    delayMaxS: 0,
                    lastAgeMin: 0,
                    ageDays: 0),
              ], seq: 1),
          throwsCodecError);
    });

    test('the sentinels decode as themselves - missing stays missing', () {
      final wire = encodeClinic(const [
        ClinicNodeFact(
            source: 1,
            prefix: 2,
            lastAgeMin: ageUnknownMin,
            ageDays: 0,
            strip: 0,
            hopsTyp: 0,
            sharePct: shareUnknownPct),
      ], seq: 1);
      final back =
          decodeClinic(wire.sublist(3)).records.single as ClinicNodeFact;
      expect(back.lastAgeMin, ageUnknownMin);
      expect(back.sharePct, shareUnknownPct);
      expect(back.snrEwma, signalUnknown);
      expect(back.snrSd, signalSdUnknown);
    });
  });
}

/// A matcher for our own exception type (never a bare `throwsException`).
final throwsCodecError = throwsA(isA<CodecError>());

void heartbeatTests() {
  group('HEARTBEAT (0x5313) - the app keep-alive', () {
    test('header only: 8 plaintext bytes, the smallest packet', () {
      final wire = encodeHeartbeat(const Heartbeat(seq: 42, origin: 0xb17e));
      expect(wire.length, 8); // type(2)+len(1)+ver(1)+seq(2)+origin(2)
      // Generic path (how traffic really arrives) routes it too.
      final decoded = decodeAny(wire) as Heartbeat;
      expect(decoded.seq, 42);
      expect(decoded.origin, 0xb17e);
      // Round-trip: the same bytes out the other side.
      expect(hexOf(encodeHeartbeat(decoded)), hexOf(wire));
    });
    test('golden agreement with the node codec', () {
      // The exact bytes the node's test pins for the same fields -
      // type(2)+len(1)+ver(1)+seq(2)+origin(2): 13 53 05 05 2a 00 7e b1.
      // The two repos stay byte-identical by construction.
      expect(hexOf(encodeHeartbeat(const Heartbeat(seq: 42, origin: 0xb17e))),
          '135305052a007eb1');
    });
  });
}
