// Golden-vector tests for the Dart wire codec.
//
// The vectors are THE SAME SIX the reference implementations pass
// (meshtech-node tests/golden_vectors.json, generated by
// tools/gen_golden.py; the TypeScript codec passes them too). Every
// test decodes the vector, asserts the fields, re-encodes, and pins
// the bytes - a byte that disagrees with the reference never ships
// (DESIGN.md law: checked against the SAME vectors).
//
// Call contract (matching the reference): the golden vectors are full
// GRP_DATA plaintexts; decodeAny strips the 3-byte envelope and
// dispatches. The typed decode* functions take the BODY only.

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:meshtech_app/codec.dart';

const Map<String, String> golden = {
  'pulse': '0153170513017eb1d20404000900280009090305080200010406',
  'sect_sum': '0253130504007eb101017e003000300300022102cdab',
  'route': '0353120502007eb101efbe38000400110003112233',
  'layout': '0553150503007eb10344d61200a01ce9ff409c0464656d6f',
  'intro': '04531e0502007eb1409c0211030748696c6c746f7024002400220105416c696365',
  // refresh: regenerated 2026-09-24 with the reference (v1.6 REFRESH_REQ:
  // version 06, +2 bytes sync_marker 0000 - the one wire change).
  'refresh': '115310060200420002efbe7eb1341200000000',
};

Uint8List bytesOf(String hex) => Uint8List.fromList([
      for (var i = 0; i < hex.length; i += 2)
        int.parse(hex.substring(i, i + 2), radix: 16),
    ]);

String hexOf(Uint8List b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

/// Decode a full golden plaintext through the generic path (the way
/// real traffic arrives), returning the typed packet.
T decodeGolden<T>(String hex) => decodeAny(bytesOf(hex)) as T;

void main() {
  group('PULSE golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final p = decodeGolden<Pulse>(golden['pulse']!);
      expect(p.seq, 275);
      expect(p.origin, 0xb17e);
      expect(p.uptimeMin, 1234);
      expect(p.rxPerHour, 4);
      expect(p.feedAirtimeSPerH, 9);
      expect(p.activeTotal, 40);
      expect(p.sectionCounts, [9, 3, 5, 8, 2, 0, 1, 4, 6]);
      expect(hexOf(encodePulse(p)), golden['pulse']);
    });
  });

  group('SECT_SUM golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final s = decodeGolden<SectSum>(golden['sect_sum']!);
      expect(s.seq, 4);
      expect(s.origin, 0xb17e);
      expect(s.sectionId, 1);
      expect(s.activeNodes, 1);
      expect(s.packetCount, 126);
      expect(s.delayP50S, 48);
      expect(s.delayP90S, 816);
      expect(s.routeStubs, [0x0221, 0xabcd]);
      expect(hexOf(encodeSectSum(s)), golden['sect_sum']);
    });
  });

  group('ROUTE golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final r = decodeGolden<Route>(golden['route']!);
      expect(r.seq, 2);
      expect(r.origin, 0xb17e);
      expect(r.sectionId, 1);
      expect(r.routeId, 0xbeef);
      expect(r.packetCount, 56);
      expect(r.delayMedS, 4);
      expect(r.lastHeardMin, 17);
      expect(r.prefixes, [0x11, 0x22, 0x33]);
      expect(hexOf(encodeRoute(r)), golden['route']);
    });
  });

  group('LAYOUT golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final l = decodeGolden<Layout>(golden['layout']!);
      expect(l.seq, 3);
      expect(l.origin, 0xb17e);
      expect(l.grid, 3);
      expect(l.centerLat, closeTo(1.2345, 1e-9));
      expect(l.centerLon, closeTo(-1.5, 1e-9));
      expect(l.spanM, 40000);
      expect(l.name, 'demo');
      expect(hexOf(encodeLayout(l)), golden['layout']);
    });
  });

  group('INTRO golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final intro = decodeGolden<Intro>(golden['intro']!);
      expect(intro.seq, 2);
      expect(intro.origin, 0xb17e);
      expect(intro.wireSpanM, 40000); // v1.5: the span rides on the wire
      expect(intro.spanM, 40000.0);
      expect(intro.entries.length, 2);
      final e1 = intro.entries[0];
      expect(e1.prefix, 0x11);
      expect(e1.name, 'Hilltop');
      expect(e1.nodeClass, nodeClassUnknown);
      expect(e1.lat, isNotNull);
      expect(e1.lon, isNotNull);
      // Deltas were 36/36 against a 40000 m span centred at (0, 0).
      final spanDeg = 40000.0 / 111320.0;
      expect(e1.lat!, closeTo(36 / 32767.0 * spanDeg, 1e-12));
      expect(e1.lon!, closeTo(36 / 32767.0 * spanDeg, 1e-12));
      final e2 = intro.entries[1];
      expect(e2.prefix, 0x22);
      expect(e2.name, 'Alice');
      expect(e2.lat, isNull);
      expect(e2.lon, isNull);
      // Re-encode from the decoded values: the position delta math
      // must round-trip exactly (decode -> encode -> same bytes).
      final rebuilt = Intro(
        seq: intro.seq,
        origin: intro.origin,
        entries: intro.entries,
        centerLat: intro.centerLat,
        centerLon: intro.centerLon,
        spanM: intro.spanM,
      );
      expect(hexOf(encodeIntro(rebuilt)), golden['intro']);
    });

    test('a caller span that disagrees with the packet is a loud error',
        () {
      final raw = bytesOf(golden['intro']!);
      final body = raw.sublist(3);
      expect(() => decodeIntro(body, spanM: 60000), throwsCodecError);
      // Agreeing span passes.
      final intro = decodeIntro(body, spanM: 40000.0);
      expect(intro.wireSpanM, 40000);
    });
  });

  group('REFRESH_REQ golden vector', () {
    test('decodes to the reference fields and re-encodes byte-identical',
        () {
      final r = decodeGolden<RefreshReq>(golden['refresh']!);
      expect(r.seq, 2);
      expect(r.origin, 0x0042);
      expect(r.kind, refreshKindRoute);
      expect(r.target, 0xbeef);
      expect(r.host, 0xb17e);
      expect(r.nonce, 0x1234);
      expect(r.spanKm, 0); // v1.3 field present, host decides
      expect(r.syncMarker, 0); // v1.6 field present, not vectored
      expect(hexOf(encodeRefreshReq(r)), golden['refresh']);
    });

    test('encode round-trips a sized ask (40 km)', () {
      final req = RefreshReq(
          seq: 9, kind: refreshKindSection, target: 5, nonce: 1, spanKm: 40);
      final back = decodeRefreshReq(encodeRefreshReq(req).sublist(3));
      expect(back.spanKm, 40);
      expect(back.kind, refreshKindSection);
      expect(back.target, 5);
    });
  });

  group('strict boundary rules (loud, never silently wrong)', () {
    test('unknown data_type is rejected', () {
      expect(() => decodeBody(0x9999, Uint8List(8)), throwsCodecError);
    });

    test('section_id 0 is reserved and rejected in a SECT_SUM', () {
      final s = const SectSum(
          seq: 1, sectionId: 0, activeNodes: 1, packetCount: 1,
          delayP50S: 0, delayP90S: 0);
      expect(() => encodeSectSum(s), throwsCodecError);
    });

    test('a too-short payload is rejected, not guessed', () {
      expect(
          () => decodePulse(Uint8List.fromList([5, 1, 0])), throwsCodecError);
      expect(
          () =>
              decodeLayout(bytesOf(golden['layout']!).sublist(3, 10)),
          throwsCodecError);
    });

    test('an unknown protocol version is rejected', () {
      final body = bytesOf(golden['pulse']!).sublist(3);
      final bad = Uint8List.fromList(body);
      bad[0] = 0x99; // version byte inside the body
      expect(() => decodePulse(bad), throwsCodecError);
    });

    test('ASCII node names round-trip through INTRO encode', () {
      final intro = Intro(
        seq: 1,
        spanM: 40000,
        entries: const [
          IntroEntry(prefix: 0x11, name: 'Hilltop',
              lat: 0.0, lon: 0.0, nodeClass: nodeClassRepeater),
        ],
      );
      final decoded =
          decodeIntro(encodeIntro(intro).sublist(3));
      expect(decoded.entries.length, 1);
      expect(decoded.entries.single.name, 'Hilltop');
      expect(decoded.entries.single.nodeClass, nodeClassRepeater);
      expect(decoded.entries.single.lat, 0.0);
    });
  });
}

/// A matcher for our own exception type (never a bare `throwsException`).
final throwsCodecError = throwsA(isA<CodecError>());
